version: '3'
services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=pangaea
      - POSTGRES_PASSWORD=pangaea
      - POSTGRES_DB=pub_sub_db
    ports:
      - "5674:5432"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  pub-sub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:2000
    environment:
      PORT: 2000
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: pangaea
      DB_PASSWORD: pangaea
      DB_NAME: pub_sub_db
      DROP_SCHEMA: 'false'
      SHOW_LOG: 'false'
      TYPEORM_SYNC: 'true'
    depends_on:
      - postgres
    command:
      [
          'node',
          'dist/src/main.js'
      ]

  #    Subscribers
  meridian:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      PORT: 3000
    depends_on:
      - pub-sub
    command:
      [
          'node',
          'dist/client/subscriber/main.js'
      ]

  luminskin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:4000
    environment:
      PORT: 4000
    depends_on:
      - pub-sub
    command:
      [
          'node',
          'dist/client/subscriber/main.js'
      ]

  menskin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:5000
    environment:
      PORT: 5000
    depends_on:
      - pub-sub
    command:
      [
          'node',
          'dist/client/subscriber/main.js'
      ]





